export const LOADING = 'LOADING'
export const LOGIN_EXITOSO = 'LOGIN_EXITOSO'
export const LOGIN_ERROR = 'LOGIN_ERROR'

export const OBTENER_USUARIO = 'OBTENER_USUARIO'
export const CERRAR_SESION = 'CERRAR_SESION'

export const USER_GET_DATA_PERSONAL = 'USER_GET_DATA_PERSONAL'
export const USER_CHANGE_DATA_PERSONAL = 'USER_CHANGE_DATA_PERSONAL'
export const USER_VALIDATE = 'USER_VALIDATE'
export const LOGOUT = 'LOGOUT'

export const LISTAR_COTIZACIONES = 'LISTAR_COTIZACIONES'
export const OBTENER_COTIZACIONES = 'OBTENER_COTIZACIONES'

export const LISTAR_REQUERIMIENTOS = 'LISTAR_REQUERIMIENTOS'
